#!/bin/bash

WALLPAPER=~/.wallpaper
XMODMAP=~/.xmodmap

# set environment variables
if [ -r "$HOME/.env" ]; then
    . $HOME/.env
fi

# set the background
[ -r $WALLPAPER ] && hsetroot -center $WALLPAPER

# remap keys
[ -r $XMODMAP ] && xmodmap $XMODMAP

# enable latchlock and sticky keys
xkbset exp 60 =sticky =twokey =latchlock
xkbset sticky -twokey latchlock

# don't annoy me!
xset -b

# start Dropbox (if installed)
if command -v dropbox
then
    dropbox start
fi

# start the panel
fbpanel &

# save my eyes!
redshift -l 53:14 &
