#!/bin/bash

WALLPAPER=~/.wallpaper
XMODMAP=~/.xmodmap

# set environment variables
if [ -r "$HOME/.env" ]; then
    . $HOME/.env
fi

# set the background
[ -r $WALLPAPER ] && hsetroot -center $WALLPAPER

# remap keys
[ -r $XMODMAP ] && xmodmap $XMODMAP

# don't annoy me!
xset -b

# run programs
dropbox start
workrave &
gtk-redshift -r -l 53:14 &
xchat --minimize=2 &
hamster-time-tracker &
blueman-applet &
gvim -class notes -O3 Notebook/Thoughtstream.md Notebook/Notebook.md Notebook/ServerLog.md
tint2 &
