#!/bin/bash

WALLPAPER="${HOME}/.wallpaper"
XMODMAP="${HOME}/.xmodmap"

# set environment variables
[ -r "${HOME}/.env" ] && source ${HOME}/.env

# set the background
[ -r "${WALLPAPER}" ] && hsetroot -center "${WALLPAPER}"

# remap keys
[ -r "${XMODMAP}" ] && xmodmap "${XMODMAP}"

# don't annoy me!
xset -b

# install Xresources
[ -r "${HOME}/.Xresources" ] && xrdb -merge "${HOME}/.Xresources"

# run programs

optrun() {
    command "$1" >& /dev/null && $@ &
}

optrun dropbox start
optrun workrave
optrun redshift -r -l 53:14
optrun synergy
optrun tint2
