" Required by vim-textobj-python
Bundle 'kana/vim-textobj-user'

Bundle 'bps/vim-textobj-python'
Bundle 'editorconfig/editorconfig-vim'
Bundle 'gmarik/vundle'
Bundle 'jmcantrell/vim-virtualenv'
Bundle 'justinmk/vim-sneak'
Bundle 'kchmck/vim-coffee-script'
Bundle 'puppetlabs/puppet-syntax-vim'
Bundle 'rking/ag.vim'
Bundle 'scrooloose/syntastic'
Bundle 'tell-k/vim-autopep8'
Bundle 'thinca/vim-quickrun'
Bundle 'tpope/vim-rails'
Bundle 'vim-scripts/UltiSnips'
Bundle 'vim-scripts/plum.vim'
