" use console instead of popups and set an icon
set guioptions=ci

" set the font
if has("gui_macvim")
    set guifont=Menlo\ Regular:h14
else
    set guifont=Inconsolata\ Medium\ 14
endif

" don't hide my pointer
set nomousehide

" stop annoying me with tooltips!
set noballooneval
