" Welcome in Vim!
set nocompatible

" Encoding
set encoding=utf8
set fileencoding=utf8

" Vundle
filetype off
set runtimepath+=~/.vim/bundle/vundle/
call vundle#rc()
source ~/.vim/bundles.vim
filetype plugin indent on

" Indentation
set expandtab
set softtabstop=4
set shiftwidth=4
set smarttab
set tabstop=4

" Searching
set incsearch
set smartcase
set ignorecase
set hlsearch
set nowrapscan

" Viewing
set nowrap
set relativenumber
set number

" Wild menu
set wildmenu

" No more annoyances!
set nomore
set backspace=2

" Status line
"" show the status line with more than one window
set laststatus=1

" Don't annoy me with swap files
set directory=$HOME/.vim/swapfiles

" Miscellaneous
set hidden
set shortmess=atI
set visualbell

" The command window
set cmdheight=1

" Don't highlight anything
set colorcolumn=

" detect file types and run appriopriate scripts
filetype on
filetype plugin on

" Enable true color support
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors

" Syntax highlight
syntax on
colorscheme base16-monokai

" Mappings
let mapleader = ","

"" make j and k use logical lines
nnoremap j gj
nnoremap k gk

"" toggling background color
function! ToggleBackground()
    if &background == "light"
        set background=dark
    else
        set background=light
    endif
endfunction

nnoremap <silent> <leader>cb :call ToggleBackground()<CR>

"" replacing
nnoremap <leader>s :%s/\<<C-r><C-w>\>//gc<Left><Left><Left>

"" split windows in a smart way
function! New()
    if 2 * winwidth(0) > 5 * winheight(0)
        execute 'vertical new +setfiletype\ ' . &filetype
    else
        execute 'new +setfiletype\ ' . &filetype
    endif
endfunction

nnoremap <C-n> :call New()<CR>

"" <leader>/ toggles search highlight
nnoremap <silent> <leader>/ :set hlsearch!<CR>

" Rg
nnoremap <leader>a :Rg<SPACE>
nnoremap <leader>w :Rg -w <C-R><C-W><CR>
nnoremap <leader>W :Rg -ws <C-R><C-W><CR>

" Testing
nnoremap <leader>tf :TestFile<CR>
nnoremap <leader>tl :TestLast<CR>
nnoremap <leader>tn :TestNearest<CR>
nnoremap <leader>ts :TestSuite<CR>
nnoremap <leader>tv :TestVisit<CR>

" UltiSnips

let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'

" Syntastic
let g:syntastic_python_checkers = ['pylint', 'pep8']
let g:syntastic_auto_loc_list=0
let g:syntastic_mode_map = {
\   'mode': 'passive',
\   'active_filetypes': [],
\   'passive_filetypes': []
\}
let g:syntastic_python_pep8_args = '--max-line-length=80'

nnoremap <leader>l :SyntasticCheck<CR>

" fzf
nnoremap <leader>f :Files<CR>
nnoremap <leader>b :Buffers<CR>
nnoremap <leader>c :Colors<CR>

" Vim-test
let test#strategy = "vimux"
