" Welcome in Vim!
set nocompatible

" Encoding
set encoding=utf8
set fileencoding=utf8

" Vundle
filetype off
set runtimepath+=~/.vim/bundle/vundle/
call vundle#rc()
source ~/.vim/bundles.vim
filetype plugin indent on

" Indentation
set expandtab
set softtabstop=4
set shiftwidth=4
set smarttab
set tabstop=4

" Searching
set incsearch
set smartcase
set ignorecase
set hlsearch
set nowrapscan

" Viewing
set nowrap
set nonumber

" Wild menu
set wildmenu

" Status line
"" show the status line with more than one window
set laststatus=1

" Don't annoy me with swap files
set directory=$HOME/.vim/swapfiles

" Miscellaneous
set hidden
set shortmess=aI
set visualbell

" The command window
set cmdheight=1

" Don't highlight anything
set colorcolumn=

" detect file types and run appriopriate scripts
filetype on
filetype plugin on

" Syntax highlight
syntax on
if has('gui_running')
    colorscheme base16-default
else
    colorscheme default
endif

" Mappings
let mapleader = ","

"" make j and k use logical lines
nnoremap j gj
nnoremap k gk

" Configuration

"" reload
nnoremap <leader>Cr :source ~/.vimrc<CR>

"" toggling numbers
nnoremap <leader>Cn :setlocal number!<CR>

"" spelling
nnoremap <silent> <leader>Cst :setlocal spell!<CR>
nnoremap <silent> <leader>Cse :setlocal spelllang=en<CR>
nnoremap <silent> <leader>Csp :setlocal spelllang=pl<CR>


"" toggling background color
function! ToggleBackground()
    if &background == "light"
        set background=dark
    else
        set background=light
    endif
endfunction

nnoremap <silent> <leader>cb :call ToggleBackground()<CR>

"" switch : and ; in the normal and visual mode
nnoremap ; :
vnoremap ; :

"" replacing
nnoremap <leader>s :%s/\<<C-r><C-w>\>//gc<Left><Left><Left>

"" split windows in a smart way
function! New()
    if 2 * winwidth(0) > 5 * winheight(0)
        execute 'vertical new +setfiletype\ ' . &filetype
    else
        execute 'new +setfiletype\ ' . &filetype
    endif
endfunction

nnoremap <C-n> :call New()<CR>

"" Fugitive mappings
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gc :Gcommit<CR>
nnoremap <leader>gr :Gread<CR>
nnoremap <leader>gw :Gwrite<CR>
nnoremap <leader>gd :Gdiff<CR>

"" <leader>/ toggles search highlight
nnoremap <silent> <leader>/ :set hlsearch!<CR>

" CtrlP
"" show files relative to the cwd
let g:ctrlp_working_path_mode=0
let g:ctrlp_custom_ignore = {
\   'dir': '\v[\/](\.git|\.hg|\.svn|man|htmlcov|node_modules)$',
\   'file': '\v\.(exe|so|dll|pyc|o)$',
\}
"" don't limit the number of files
let g:ctrlp_max_files=0
let g:ctrlp_map = '<leader>p'
nnoremap <leader>P :CtrlPBuffer<CR>

" Ag
nnoremap <leader>a :Ag!<SPACE>
nnoremap <leader>w :Ag! -w <C-R><C-W><CR>

" UltiSnips

"" cannot use snippets because it's reserved for SnipMate snippets
let g:UltiSnipsSnippetDirectories = ['snips']

"" we need to use CTRL-j in order to avoid conflicts with YCM
let g:UltiSnipsExpandTrigger = '<c-j>'

" make
nnoremap <leader>m :make<SPACE>
nnoremap <leader>M :make<CR>

" Syntastic
let g:syntastic_python_checkers = ['pylint', 'pep8']
let g:syntastic_auto_loc_list=0
let g:syntastic_mode_map = {
\   'mode': 'passive',
\   'active_filetypes': [],
\   'passive_filetypes': []
\}
let g:syntastic_python_pep8_args = '--max-line-length=80'

nnoremap <leader>l :SyntasticCheck<CR>

" YouCompleteMe
let g:ycm_use_ultisnips_completer = 0

" Shell and Thunar
if has('gui_running')
    nnoremap <leader>x :silent :!terminal >& /dev/null &<CR>
else
    nnoremap <leader>x :shell<CR>
endif

nnoremap <leader>t :silent :!thunar &> /dev/null &<CR>
